# POST http://localhost:4000/api/comment/addComment
# Content-Type: application/json

# {
#   "postId": 1,
#   "titleOfThePost": "The Future of AI in Healthcare",
#   "text": "Even if that’s true, maintaining order was their duty. It’s not black and white.",
#   "author": "Ashar Azeem",
#   "profile": "1",
#   "commenterGender": "Male",
#   "commenterCountry": "Pakistan",
#   "heirarchyOfCommments":{
#   "text": "The military’s involvement was justified given the chaos at the border.",
#   "replies": [
#     {
#       "text": "Justified? They used excessive force on unarmed civilians!",
#       "replies": [
#         {
#           "text": "You’re exaggerating. The civilians were throwing stones and blocking aid trucks.",
#           "replies": [
#           ]
          
#         }
#       ]
#     }
#   ]
# }
# ,
#   "parentId": "690b7bee220615953b2bf1c1",
#   "clusters": ["withMilitary", "againstMilitary", "neutral"],
#   "uploadTime": "2025-11-05T14:30:00.000Z",
#   "userId": 40
# }




# POST http://localhost:4000/api/comment/addComment
# Content-Type: application/json

# {
#   "postId": 30,
#   "titleOfThePost": "Military Spending Debate",
#   "text": "A balanced approach is better: maintain necessary defense but don’t overspend at the cost of citizens.",
#   "author": "human-cattle-hLKi",
#   "profile": 5,
#   "commenterGender": "Female",
#   "commenterCountry": "Pakistan",
#   "parentId": null,
#   "clusters": ["should increase the budget","should not increase the budget"],
#   "uploadTime": "2025-11-12T18:09:00Z",
#   "userId": 45,
#   "parentComment": null
# }









GET http://localhost:4000/api/user/users
Content-Type: application/json

{
  "userName":"MA"

  }






# PUT http://localhost:4000/api/message/updateMessage
# Content-Type: application/json

# {
#   "messageId":"b3f84749-6a8e-4909-b0a8-2171db7fd47e",
#   "reaction":{"emoji":"😂","reactedUser":"34"},
#   "notifyUserId":"44"
# }










# POST http://127.0.0.1:8000/classify
# Content-Type: application/json


# {
#   "comment": "The army only shows up when they want to control everything.",
#   "clusters": ["criticize army", "supports army", "neutral"]
# }

