# PUT http://localhost:4000/api/message/updateSeenStatus
# Content-Type: application/json

# {
#   "chatId":"598a279f-aec5-48d4-90a5-d5446c54d0d1",
#   "userId":"34",
#   "receiverId":"44"
# }











# PUT http://localhost:4000/api/message/updateMessage
# Content-Type: application/json

# {
#   "messageId":"b3f84749-6a8e-4909-b0a8-2171db7fd47e",
#   "reaction":{"emoji":"😂","reactedUser":"34"},
#   "notifyUserId":"44"
# }










POST http://127.0.0.1:8000/classify
Content-Type: application/json


{
  "comment": "The army only shows up when they want to control everything.",
  "clusters": ["criticize army", "supports army", "neutral"]
}

